# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('ip', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='IP')),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
                ('tunn', models.CharField(max_length=50, verbose_name='Tunnel')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.AddField(
            model_name='ping',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sites'),
        ),
    ]
