# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20151208_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='ip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP'),
        ),
    ]
