# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20151208_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ping',
            old_name='site',
            new_name='ip',
        ),
    ]
