# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20151208_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='IP',
        ),
    ]
