# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20151208_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
