# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20151208_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='ip',
        ),
        migrations.AddField(
            model_name='ping',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
