# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20151208_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='tunn',
        ),
        migrations.AddField(
            model_name='ip',
            name='tunName',
            field=models.CharField(default=1, max_length=50, verbose_name='Tunnel Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='tunType',
            field=models.CharField(default=2, max_length=3, verbose_name='Tunnel Type'),
            preserve_default=False,
        ),
    ]
