# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20151209_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='date',
            field=models.CharField(default=3, max_length=15, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='reach',
            field=models.BooleanField(default=False),
        ),
    ]
