# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20151209_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='reach',
        ),
    ]
