# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_ping_reach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='reach',
            field=models.CharField(max_length=5, verbose_name='Reachable'),
        ),
    ]
