# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20151209_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='disk',
            field=models.PositiveIntegerField(default=4, verbose_name='Disk Usage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='pe',
            field=models.PositiveIntegerField(default=3, verbose_name='PE Count'),
            preserve_default=False,
        ),
    ]
